#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib/mkpw'

mkpw = Mkpw.new

num_words = (ARGV.shift || 2).to_i
how_many = (ARGV.shift || 2).to_i
how_many.times do |y|
  word_color = y.odd? ? :blue : :light_green
  sep_color = :magenta

  components = mkpw.generate_word_pass(word_qty: num_words)
  components[:words] << '' if components[:words].count == 1
  length = 0
  thy_royal_pass = components[:words].map do |w|
    length += w.length + components[:seperator].length
    w.colorize(word_color)
  end.join(components[:seperator].colorize(sep_color))

  puts "#{length} chars =>  #{thy_royal_pass}"
end
